import type { ExamplePreset } from "./types";

export const examplePresets: ExamplePreset[] = [
  {
    id: "example-1",
    label: "INTJ → ENFP · 恋爱",
    senderType: "INTJ",
    receiverType: "ENFP",
    scenario: "恋爱关系",
    customScenario: "",
    originalText: "这个计划逻辑上不完整，风险太高。",
  },
  {
    id: "example-2",
    label: "ENFP → INTJ · 恋爱",
    senderType: "ENFP",
    receiverType: "INTJ",
    scenario: "恋爱关系",
    customScenario: "",
    originalText: "我只是觉得最近我们之间没有以前那种感觉了。",
  },
  {
    id: "example-3",
    label: "INFP → ESTJ · 工作",
    senderType: "INFP",
    receiverType: "ESTJ",
    scenario: "工作反馈",
    customScenario: "",
    originalText: "我觉得这个安排让我有点不舒服，但我也说不清楚哪里不对。",
  },
  {
    id: "example-4",
    label: "ENTJ → ISFP · 团队",
    senderType: "ENTJ",
    receiverType: "ISFP",
    scenario: "团队协作",
    customScenario: "",
    originalText: "这个任务本周必须推进，你需要尽快给我一个明确结果。",
  },
  {
    id: "example-5",
    label: "ENTP → ISTJ · 项目",
    senderType: "ENTP",
    receiverType: "ISTJ",
    scenario: "团队协作",
    customScenario: "",
    originalText: "要不我们先别按原计划走，我突然想到一个更有意思的方向。",
  },
  {
    id: "example-6",
    label: "ISFJ → ESTP · 朋友",
    senderType: "ISFJ",
    receiverType: "ESTP",
    scenario: "朋友沟通",
    customScenario: "",
    originalText: "我不是不想去，只是觉得如果安排能再稳定一点我会更安心。",
  },
];
